# fly.toml app configuration file generated for midday-worker on 2025-06-16T12:36:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'midday-worker'
primary_region = 'fra'

[build]

[[restart]]
  policy = "always"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
