# fly.toml app configuration file generated for midday-worker on 2025-06-16T12:36:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'midday-worker'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

# Removed [http_service] section - workers don't need public HTTP access
# This worker processes background jobs from Redis queues only

[processes]
  app = ""

[processes.app]
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  max_machines_running = 2

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
