# fly.toml app configuration file generated for midday-worker on 2025-06-16T12:36:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'midday-worker'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[restart]]
  policy = "always"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
