name: Fly Deploy Worker
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - apps/worker/**
      - packages/db/**
      - packages/email/**
jobs:
  deploy:
    name: 🚀 Deploy to Fly Worker
    runs-on: ubuntu-latest
    concurrency: fly-worker
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: 🏗 Build @midday/engine
        run: bunx turbo run build --filter=@midday/engine...
      - name: 🔦 Run linter
        run: bun run lint
        working-directory: ./apps/worker
      - name: 🪐 Check TypeScript
        run: bun run typecheck
        working-directory: ./apps/worker
      - name: 🧪 Run unit tests
        run: bun run test
        working-directory: ./apps/worker
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --dockerfile apps/worker/Dockerfile --config apps/worker/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}